name: Base
fields:
  - key: lang
    type: input
    rules:

  - key: header
    type: fieldset
    fields:
      - key: links
        type: array
        fields:
          - key: title
            type: input
            rules: required
          - key: url
            type: input
            rules: required
